### ISSUE TITLE
How to use this library without clicking the view? 

### ISSUE THREAD

**Issue by woshizsx** [wasabeef/Blurry#11]
I have the same question: how to use this library without clicking the view? 
Thanks for anyone to give me some info.

**Comment by wasabeef** [comment]
@woshizsx 

This it?

https://github.com/wasabeef/glide-transformations
https://github.com/wasabeef/picasso-transformations

```
Glide.with(this).load(R.drawable.demo)
        .bitmapTransform(new BlurTransformation(context))
        .into((ImageView) findViewById(R.id.image));
```

**Comment by woshizsx** [comment]
Got it! Thanks a lot!!
