### ISSUE TITLE
build error  Duplicate files  "armeabi-v7a/librsjni.so"

### ISSUE THREAD

**Issue by yilylong** [wasabeef/Blurry#22]
Error:duplicate files during packaging of APK E:\MyAndroidSudioProgects\ChongBaoFunny\demo\build\outputs\apk\demo-debug-unaligned.apk
	Path in archive: lib/armeabi-v7a/librsjni.so
	Origin 1: E:\MyAndroidSudioProgects\ChongBaoFunny\demo\build\intermediates\exploded-aar\jp.wasabeef\blurry\1.0.5\jni\armeabi-v7a\librsjni.so
	Origin 2: D:\work\AndroidSDK\build-tools\22.0.1\renderscript\lib\packaged\armeabi-v7a\librsjni.so
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/armeabi-v7a/librsjni.so'
	  }
	}
Error:Execution failed for task ':demo:packageDebug'.
> Duplicate files copied in APK lib/armeabi-v7a/librsjni.so
	File 1: E:\MyAndroidSudioProgects\ChongBaoFunny\demo\build\intermediates\exploded-aar\jp.wasabeef\blurry\1.0.5\jni\armeabi-v7a\librsjni.so
	File 2: D:\work\AndroidSDK\build-tools\22.0.1\renderscript\lib\packaged\armeabi-v7a\librsjni.so

I have added
    packagingOptions {
	exclude 'lib/armeabi-v7a/librsjni.so'
}
in my build.gradle but it still report this error

**Comment by chentao7v** [comment]
I have the same issue,somebody help me

**Comment by chentao7v** [comment]
I do it like this, and it works:
> first , in the root `build.grandle`

```
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
> second
user apkSplits replace refConfig in the build.grale of you app.
link: http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits

**Comment by yilylong** [comment]
when  i update  gradle version to 1.5.0 it works well
