### ISSUE TITLE
Crash using on Oncreate

### ISSUE THREAD

**Issue by SluggedGerm2** [wasabeef/Blurry#52]
It crash using it into onCreate. I solved using a hendler like
final Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                //Do something after 1000ms
                Blurry.with(getApplicationContext()).capture(m_Cover).into((ImageView) findViewById(R.id.dash_imageView_cover_to_blurry));
            }
        }, 150);

Are there any solution to have blur effect without delay?

**Comment by rafa0809** [comment]
This approach worked for me:

```
final ViewTreeObserver viewTreeObserver = container.getViewTreeObserver();
viewTreeObserver.addOnGlobalLayoutListener( new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                setupBlurEffect();
                viewTreeObserver.removeOnGlobalLayoutListener( this );
            }
        } );
```

**Comment by SluggedGerm2** [comment]
Thanks, it work fine :)
