### ISSUE TITLE
Build Error : Could not find jp.wasabeef:blurry:3.x.x

### ISSUE THREAD

**Issue by dragonStandard123** [wasabeef/Blurry#91]
Gradle cant find this module.

> classpath 'com.android.tools.build:gradle:3.2.0'

> compileSdkVersion 28
> targetSdkVersion 28
> 
> dependencies {
>     compile 'jp.wasabeef:blurry:3.x.x'
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation 'com.android.support:appcompat-v7:28.0.0'
>     implementation 'com.android.support:design:28.0.0'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     implementation 'com.android.support:support-vector-drawable:28.0.0'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner 1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> }
> 

The error message is ...
> Could not find jp.wasabeef:blurry:3.x.x.
>   Searched in the following locations:
>       file:/E:/Applications/Android/SDK/extras/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.pom
>       file:/E:/Applications/Android/SDK/extras/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.jar
>       file:/E:/Applications/Android/SDK/extras/google/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.pom
>       file:/E:/Applications/Android/SDK/extras/google/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.jar
>       file:/E:/Applications/Android/SDK/extras/android/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.pom
>       file:/E:/Applications/Android/SDK/extras/android/m2repository/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.jar
>       https://dl.google.com/dl/android/maven2/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.pom
>       https://dl.google.com/dl/android/maven2/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.jar
>       https://jcenter.bintray.com/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.pom
>       https://jcenter.bintray.com/jp/wasabeef/blurry/3.x.x/blurry-3.x.x.jar
>   Required by:
>       project :app

What's wrong with me?

So I have cloned PR and tried to build but failed with an error like this...
> FAILURE: Build failed with an exception.
> * Where:
> Build file 'C:\Users\DRAGON\Downloads\Blurry-master\example\build.gradle' line: 11
> 
> * What went wrong:
> A problem occurred evaluating project ':example'.
> Could not find method versionCode() for arguments [3.0.0] on DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=14, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=28, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

How can I build this successfully?
I want this module eagerly :heart:

**Comment by VaibhavNalawade** [comment]
Same here
ERROR: Failed to resolve: jp.wasabeef:blurry:3.x.x
Show in Project Structure dialog
Affected Modules: app

**Comment by Sanaebadi97** [comment]
Hi , 
Try this , be Fixed :

` implementation 'jp.wasabeef:blurry:2.1.0'`

**Comment by VivekThummar52** [comment]
Which is the updated version if anyone knows??

**Comment by dhorajiaabhishek** [comment]
Hey try this it works
implementation  'jp.wasabeef:blurry:4.0.0'
