### ISSUE TITLE
acync and onto after update  4.0.0

### ISSUE THREAD

**Issue by ifyousleep** [wasabeef/Blurry#99]
There is this code that works on version 3

` Blurry.with(context)`
`.radius(8)`
               ` .sampling(8)`
                `.async { make any func }`
                `.animate(any duration)`
                `.onto(any FrameLayout)`

But on version 4, I cannot use this code and cannot reproduce the actions I need.
Can you help me with the update?

**Comment by wasabeef** [comment]
@ifyousleep 

Yes, We added another async method.
```kotlin
Blurry.with(context)
  .radius(8)
  .sampling(8)
  .animate(any duration)
  .getAsync { bitmap ->
    layout.addView(any ImageView with using bitmap)
  }
```

**Comment by ifyousleep** [comment]
@wasabeef thanks
